services:
  # 1. Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: awp_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=awp_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Servicio de Backend (FastAPI)
  backend:
    container_name: awp_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/awp_db

  # 3. Servicio de Frontend (React / Vite)
  frontend:
    container_name: awp_frontend
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      # AÑADIDO: Esta variable es leída por React/Vite para saber dónde está el Backend
      - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data: